* debian/aprx.init:     Pleasing init-script behaviour during package re-install
* telemetry.c, doc/aprx-manual.odt:
    Stagger telemetry transmissions a bit.
    All RF reported telemetry sources are reported at the same time,
    but telemetry data is time-wise separated from labels, and labels
    are sent so that 3 different labels are sent every 2 hours, and
    total label carouselle time is 6 hours.

diff --git a/debian/aprx.init b/debian/aprx.init
--- a/debian/aprx.init
+++ b/debian/aprx.init
@@ -40,7 +40,7 @@ case "$1" in
 	;;
   stop)
 	echo -n "Stopping $DESC: "
-	set -e
+	#set -e  # don't upset if it fails..
 	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid  \
 		--exec $DAEMON --oknodo
 	echo
@@ -72,10 +72,9 @@ case "$1" in
 	;;
   restart)
     echo -n "Restarting $DESC: "
-	start-stop-daemon --stop --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON
-	sleep 1
 	set -e
+	start-stop-daemon --stop --quiet --pidfile \
+		/var/run/$NAME.pid --exec $DAEMON --oknodo
 	start-stop-daemon --start --quiet --pidfile \
 		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
 	echo "$NAME."
